// Vitarex demo content. Replace with real product data, prices and photos.

const TRANSLATIONS = {
  ru: {
    demo_banner: "Демо-версия сайта. Товары, цены и фото — примеры для наполнения. Свяжитесь с нами, чтобы обсудить финальный вариант.",
    nav_about: "О нас",
    nav_catalog: "Каталог",
    nav_advantages: "Преимущества",
    nav_steps: "Как заказать",
    nav_reviews: "Отзывы",
    nav_faq: "FAQ",
    nav_contacts: "Контакты",
    header_cta: "Заказать",
    hero_eyebrow: "Premium suv tozalash filtri",
    hero_title_html: "Чистая вода в <em>каждом доме</em> — с фильтрами Vitarex",
    hero_chip_steps: "7 ступеней очистки",
    hero_chip_warranty: "Гарантия на монтаж",
    hero_sub: "Многоступенчатая очистка, простая установка и забота о здоровье вашей семьи. Каталог фильтров под любые задачи — от кухни до целого дома.",
    hero_cta_catalog: "Смотреть каталог",
    hero_cta_contact: "Получить консультацию",
    stat_followers: "подписчиков в Instagram",
    stat_steps_value: "до 7 ступеней",
    stat_steps: "очистки воды",
    stat_warranty_value: "гарантия",
    stat_warranty: "на фильтры и монтаж",
    about_eyebrow: "О компании",
    about_title: "Vitarex — гарантия здоровой и чистой воды",
    about_p1: "Мы поставляем и устанавливаем премиальные системы очистки воды для дома, офиса и бизнеса. Наша миссия — чтобы в каждом доме была вода, которой можно доверять.",
    about_p2: "Работаем напрямую с клиентом: подбираем модель под состав воды и задачи, доставляем, устанавливаем и остаёмся на связи для обслуживания.",
    about_li1: "Подбор фильтра под воду вашего района",
    about_li2: "Установка мастером и настройка системы",
    about_li3: "Сервисное обслуживание и замена картриджей",
    quiz_eyebrow: "Тест за 30 секунд",
    quiz_title: "Не знаете, какую модель выбрать?",
    quiz_sub: "Ответьте на 3 вопроса — подскажем подходящую модель Vitarex.",
    quiz_step: "Вопрос {c} из {t}",
    quiz_back: "Назад",
    quiz_result_badge: "Рекомендуем вам",
    quiz_result_hint: "Рекомендация основана на ваших ответах и не заменяет консультацию мастера.",
    quiz_restart: "Пройти заново",
    quiz_view_catalog: "Смотреть весь каталог",
    quiz_order: "Заказать эту модель",
    catalog_eyebrow: "Каталог",
    catalog_title: "Модели фильтров Vitarex",
    catalog_sub: "Демо-линейка для примера. Пришлите реальные модели, характеристики и цены — заменим карточки на актуальные.",
    catalog_compare_link: "Сравнить характеристики моделей",
    compare_eyebrow: "Сравнение",
    compare_title: "Сравните модели",
    compare_sub: "Бета-версия таблицы с демо-моделями — после добавления реального каталога заменим на актуальное сравнение.",
    compare_row_steps: "Ступени очистки",
    compare_row_resource: "Ресурс картриджа",
    compare_row_performance: "Производительность",
    compare_row_bestfor: "Рекомендуется для",
    compare_row_price: "Цена",
    adv_eyebrow: "Почему мы",
    adv_title: "Преимущества Vitarex",
    steps_eyebrow: "Процесс",
    steps_title: "Как оформить заказ",
    reviews_eyebrow: "Отзывы",
    reviews_title: "Что говорят наши клиенты",
    reviews_sub: "Демо-отзывы для примера оформления блока — заменим на реальные отзывы клиентов.",
    faq_eyebrow: "Вопросы и ответы",
    faq_title: "Частые вопросы",
    faq_sub: "Не нашли ответ — напишите нам в Telegram, ответим лично.",
    contact_eyebrow: "Контакты",
    contact_title: "Готовы подобрать фильтр для вашего дома?",
    contact_sub: "Оставьте заявку или напишите нам напрямую — ответим и поможем с выбором модели.",
    form_title: "Быстрая заявка",
    form_name: "Ваше имя",
    form_name_ph: "Имя",
    form_phone: "Телефон",
    form_model: "Интересующая модель",
    form_submit: "Отправить в Telegram",
    form_hint: "Кнопка откроет Telegram с готовым сообщением для @Vitarex_admin.",
    footer_tag: "Premium suv tozalash filtri — sog'lom va toza suv kafolati.",
    footer_rights: "Все права защищены.",
    footer_demo: "Демо-сайт, созданный для наполнения реальными данными.",
    price_from: "от",
    price_currency: "сум",
    order_btn: "Заказать",
  },
  uz: {
    demo_banner: "Sayt demo-versiyasi. Mahsulotlar, narxlar va suratlar — namuna sifatida keltirilgan. Yakuniy variantni muhokama qilish uchun biz bilan bog'laning.",
    nav_about: "Biz haqimizda",
    nav_catalog: "Katalog",
    nav_advantages: "Afzalliklar",
    nav_steps: "Qanday buyurtma qilish",
    nav_reviews: "Fikrlar",
    nav_faq: "FAQ",
    nav_contacts: "Aloqa",
    header_cta: "Buyurtma berish",
    hero_eyebrow: "Premium suv tozalash filtri",
    hero_title_html: "Har bir <em>uyda toza suv</em> — Vitarex filtrlari bilan",
    hero_chip_steps: "7 bosqichli tozalash",
    hero_chip_warranty: "Montaj uchun kafolat",
    hero_sub: "Ko'p bosqichli tozalash, oson o'rnatish va oilangiz salomatligi haqida g'amxo'rlik. Har qanday ehtiyoj uchun filtrlar katalogi — oshxonadan butun uygacha.",
    hero_cta_catalog: "Katalogni ko'rish",
    hero_cta_contact: "Konsultatsiya olish",
    stat_followers: "Instagram obunachilari",
    stat_steps_value: "7 bosqichgacha",
    stat_steps: "suv tozalash",
    stat_warranty_value: "kafolat",
    stat_warranty: "filtr va montaj uchun",
    about_eyebrow: "Kompaniya haqida",
    about_title: "Vitarex — sog'lom va toza suv kafolati",
    about_p1: "Biz uy, ofis va biznes uchun premium suv tozalash tizimlarini yetkazib beramiz va o'rnatamiz. Bizning maqsadimiz — har bir uyda ishonch bildirsa bo'ladigan suv bo'lishi.",
    about_p2: "Mijoz bilan bevosita ishlaymiz: suv tarkibi va ehtiyojlarga qarab model tanlaymiz, yetkazib beramiz, o'rnatamiz va xizmat ko'rsatish uchun aloqada bo'lamiz.",
    about_li1: "Hududingiz suviga mos filtr tanlash",
    about_li2: "Usta tomonidan o'rnatish va sozlash",
    about_li3: "Servis xizmati va kartrijlarni almashtirish",
    quiz_eyebrow: "30 soniyalik test",
    quiz_title: "Qaysi modelni tanlashni bilmayapsizmi?",
    quiz_sub: "3 ta savolga javob bering — mos Vitarex modelini taklif qilamiz.",
    quiz_step: "Savol {c} / {t}",
    quiz_back: "Orqaga",
    quiz_result_badge: "Sizga tavsiya etamiz",
    quiz_result_hint: "Tavsiya javoblaringizga asoslangan va usta konsultatsiyasini almashtirmaydi.",
    quiz_restart: "Qayta boshlash",
    quiz_view_catalog: "Butun katalogni ko'rish",
    quiz_order: "Shu modelni buyurtma qilish",
    catalog_eyebrow: "Katalog",
    catalog_title: "Vitarex filtr modellari",
    catalog_sub: "Namuna uchun demo qator. Haqiqiy modellar, xususiyatlar va narxlarni yuboring — kartochkalarni yangilaymiz.",
    catalog_compare_link: "Model xususiyatlarini solishtirish",
    compare_eyebrow: "Solishtirish",
    compare_title: "Modellarni solishtiring",
    compare_sub: "Demo-modellar bilan beta jadval — haqiqiy katalog qo'shilgach, aniq solishtirishga almashtiramiz.",
    compare_row_steps: "Tozalash bosqichlari",
    compare_row_resource: "Kartrij resursi",
    compare_row_performance: "Unumdorlik",
    compare_row_bestfor: "Nima uchun mos",
    compare_row_price: "Narxi",
    adv_eyebrow: "Nega aynan biz",
    adv_title: "Vitarex afzalliklari",
    steps_eyebrow: "Jarayon",
    steps_title: "Buyurtmani qanday rasmiylashtirish",
    reviews_eyebrow: "Fikrlar",
    reviews_title: "Mijozlarimiz nima deyishadi",
    reviews_sub: "Blok dizayni uchun demo-fikrlar — haqiqiy mijoz fikrlariga almashtiramiz.",
    faq_eyebrow: "Savol-javob",
    faq_title: "Tez-tez so'raladigan savollar",
    faq_sub: "Javobini topolmadingizmi — Telegramga yozing, shaxsan javob beramiz.",
    contact_eyebrow: "Aloqa",
    contact_title: "Uyingiz uchun filtr tanlashga tayyormisiz?",
    contact_sub: "Ariza qoldiring yoki bevosita yozing — javob berib, model tanlashda yordam beramiz.",
    form_title: "Tezkor ariza",
    form_name: "Ismingiz",
    form_name_ph: "Ism",
    form_phone: "Telefon",
    form_model: "Qiziqtirgan model",
    form_submit: "Telegramga yuborish",
    form_hint: "Tugma @Vitarex_admin uchun tayyor xabar bilan Telegramni ochadi.",
    footer_tag: "Premium suv tozalash filtri — sog'lom va toza suv kafolati.",
    footer_rights: "Barcha huquqlar himoyalangan.",
    footer_demo: "Haqiqiy ma'lumotlar bilan to'ldirish uchun yaratilgan demo-sayt.",
    price_from: "dan",
    price_currency: "so'm",
    order_btn: "Buyurtma berish",
  },
};

const CATALOG = {
  ru: [
    {
      icon: "tap",
      featured: true,
      badge: "Хит продаж",
      name: "Vitarex Compact",
      desc: "Компактный фильтр под мойку для кухни",
      specs: ["3 ступени очистки", "Установка под мойкой", "Ресурс — 6 месяцев"],
      price: "890 000",
      steps: "3",
      resource: "6 мес.",
      performance: "2 л/мин",
      bestFor: "Кухня",
    },
    {
      icon: "home",
      badge: "Для дома",
      name: "Vitarex Standard",
      desc: "Универсальная система для всей квартиры",
      specs: ["5 ступеней очистки", "Без хлора и запаха", "Ресурс — 8 месяцев"],
      price: "1 490 000",
      steps: "5",
      resource: "8 мес.",
      performance: "3 л/мин",
      bestFor: "Квартира",
    },
    {
      icon: "gauge",
      badge: "Обратный осмос",
      name: "Vitarex Pro RO",
      desc: "Глубокая очистка методом обратного осмоса",
      specs: ["7 ступеней + мембрана RO", "Минерализация на выходе", "Кран в комплекте"],
      price: "2 390 000",
      steps: "7 + RO",
      resource: "10 мес.",
      performance: "2,5 л/мин",
      bestFor: "Жёсткая вода",
    },
    {
      icon: "building",
      badge: "Для бизнеса",
      name: "Vitarex Ultra",
      desc: "Производительная система для офиса и бизнеса",
      specs: ["Высокая производительность", "Умный индикатор ресурса", "Для кафе и офисов"],
      price: "3 990 000",
      steps: "7 + RO",
      resource: "12 мес.",
      performance: "6 л/мин",
      bestFor: "Кафе / офис",
    },
  ],
  uz: [
    {
      icon: "tap",
      featured: true,
      badge: "Ko'p sotiladi",
      name: "Vitarex Compact",
      desc: "Oshxona uchun mo'ljallangan kompakt filtr",
      specs: ["3 bosqichli tozalash", "Rakovina ostiga o'rnatish", "Resurs — 6 oy"],
      price: "890 000",
      steps: "3",
      resource: "6 oy",
      performance: "2 l/daq",
      bestFor: "Oshxona",
    },
    {
      icon: "home",
      badge: "Uy uchun",
      name: "Vitarex Standard",
      desc: "Butun kvartira uchun universal tizim",
      specs: ["5 bosqichli tozalash", "Xlor va hidsiz", "Resurs — 8 oy"],
      price: "1 490 000",
      steps: "5",
      resource: "8 oy",
      performance: "3 l/daq",
      bestFor: "Kvartira",
    },
    {
      icon: "gauge",
      badge: "Teskari osmos",
      name: "Vitarex Pro RO",
      desc: "Teskari osmos usulida chuqur tozalash",
      specs: ["7 bosqich + RO membranasi", "Chiqishda minerallashtirish", "Kran komplektda"],
      price: "2 390 000",
      steps: "7 + RO",
      resource: "10 oy",
      performance: "2,5 l/daq",
      bestFor: "Qattiq suv",
    },
    {
      icon: "building",
      badge: "Biznes uchun",
      name: "Vitarex Ultra",
      desc: "Ofis va biznes uchun yuqori unumli tizim",
      specs: ["Yuqori unumdorlik", "Aqlli resurs indikatori", "Kafe va ofislar uchun"],
      price: "3 990 000",
      steps: "7 + RO",
      resource: "12 oy",
      performance: "6 l/daq",
      bestFor: "Kafe / ofis",
    },
  ],
};

const ADVANTAGES = {
  ru: [
    { icon: "layers", title: "Многоступенчатая очистка", text: "Удаляем хлор, тяжёлые металлы, бактерии и механические примеси." },
    { icon: "wrench", title: "Профессиональная установка", text: "Монтаж выполняют обученные мастера с гарантией на работу." },
    { icon: "truck", title: "Быстрая доставка", text: "Привозим и устанавливаем в удобное для вас время." },
    { icon: "refresh", title: "Сервис и картриджи", text: "Напоминаем о замене и всегда есть расходники в наличии." },
    { icon: "shield", title: "Гарантия качества", text: "Официальная гарантия на оборудование и монтажные работы." },
    { icon: "chat", title: "Поддержка 24/7", text: "На связи в Telegram и по телефону для любых вопросов." },
  ],
  uz: [
    { icon: "layers", title: "Ko'p bosqichli tozalash", text: "Xlor, og'ir metallar, bakteriya va mexanik aralashmalarni yo'qotamiz." },
    { icon: "wrench", title: "Professional o'rnatish", text: "Montajni tajribali ustalar kafolat bilan bajaradi." },
    { icon: "truck", title: "Tezkor yetkazib berish", text: "Sizga qulay vaqtda olib kelamiz va o'rnatamiz." },
    { icon: "refresh", title: "Servis va kartrijlar", text: "Almashtirish vaqtini eslatib turamiz, ehtiyot qismlar doim mavjud." },
    { icon: "shield", title: "Sifat kafolati", text: "Uskuna va montaj ishlariga rasmiy kafolat beramiz." },
    { icon: "chat", title: "24/7 qo'llab-quvvatlash", text: "Telegram va telefon orqali har doim aloqadamiz." },
  ],
};

const STEPS = {
  ru: [
    { title: "Выбираете модель", text: "Смотрите каталог или пишете нам — поможем подобрать фильтр." },
    { title: "Оформляете заявку", text: "Оставляете контакты в форме или пишете в Telegram." },
    { title: "Согласовываем детали", text: "Уточняем адрес, дату и особенности установки." },
    { title: "Устанавливаем и запускаем", text: "Мастер приезжает, монтирует систему и всё проверяет." },
  ],
  uz: [
    { title: "Model tanlaysiz", text: "Katalogni ko'ring yoki bizga yozing — filtr tanlashda yordam beramiz." },
    { title: "Ariza qoldirasiz", text: "Formada kontaktlaringizni qoldiring yoki Telegramga yozing." },
    { title: "Tafsilotlarni kelishamiz", text: "Manzil, sana va o'rnatish xususiyatlarini aniqlashtiramiz." },
    { title: "O'rnatib, ishga tushiramiz", text: "Usta kelib tizimni o'rnatadi va hammasini tekshiradi." },
  ],
};

const REVIEWS = {
  ru: [
    { name: "Азиз Т.", text: "Установили Vitarex Standard на кухне — вода стала намного чище на вкус. Мастер приехал вовремя и всё объяснил.", initial: "А" },
    { name: "Мадина Р.", text: "Заказывали Pro RO для дома. Понравилось, что подобрали модель именно под нашу воду.", initial: "М" },
    { name: "Шерзод К.", text: "Отличный сервис — напомнили о замене картриджа заранее. Рекомендую.", initial: "Ш" },
    { name: "Дилноза С.", text: "Compact встал под мойку без переделок кухни. Ушёл привкус хлора буквально с первого дня.", initial: "Д" },
    { name: "Жасур Б.", text: "От заявки до установки прошло всего два дня. Мастер аккуратно всё смонтировал и убрал за собой.", initial: "Ж" },
    { name: "Нигора А.", text: "Поставили Ultra в кафе — гости стали заказывать больше напитков на воде. Производительности хватает с запасом.", initial: "Н" },
    { name: "Отабек М.", text: "Писал в Telegram с вопросами перед покупкой — отвечали быстро и по делу, без навязывания.", initial: "О" },
    { name: "Камола Ю.", text: "Ребёнок наконец пьёт воду из-под фильтра без капризов. Вкус и правда стал мягче.", initial: "К" },
  ],
  uz: [
    { name: "Aziz T.", text: "Oshxonaga Vitarex Standard o'rnatildi — suv mazasi ancha yaxshilandi. Usta o'z vaqtida keldi va hammasini tushuntirdi.", initial: "A" },
    { name: "Madina R.", text: "Uy uchun Pro RO buyurtma qildik. Aynan bizning suvimizga mos model tanlashgani yoqdi.", initial: "M" },
    { name: "Sherzod Q.", text: "Ajoyib servis — kartrijni almashtirish vaqtini oldindan eslatishdi. Tavsiya qilaman.", initial: "S" },
    { name: "Dilnoza S.", text: "Compact rakovina ostiga oshxonani qayta ta'mirlamasdan o'rnatildi. Xlor hidi birinchi kunidan yo'qoldi.", initial: "D" },
    { name: "Jasur B.", text: "Arizadan o'rnatishgacha bor-yo'g'i ikki kun ketdi. Usta hammasini toza va aniq qildi.", initial: "J" },
    { name: "Nigora A.", text: "Kafega Ultra o'rnatdik — unumdorligi yetarli, mehmonlar suvli ichimliklarni ko'proq buyurtma qila boshladi.", initial: "N" },
    { name: "Otabek M.", text: "Sotib olishdan oldin Telegramga savol yozgandim — tez va aniq javob berishdi, ortiqcha taklif qilishmadi.", initial: "O" },
    { name: "Kamola Yu.", text: "Bolam endi filtr suvini injiqliksiz ichadi. Mazasi haqiqatan ham yumshoqroq bo'ldi.", initial: "K" },
  ],
};

const FAQ = {
  ru: [
    { q: "Как часто нужно менять картриджи?", a: "В среднем раз в 6–12 месяцев в зависимости от модели и качества исходной воды. Точный интервал указывается в паспорте конкретного фильтра, а мы напоминаем о замене заранее." },
    { q: "Подходит ли фильтр для очень жёсткой воды?", a: "Да, для жёсткой воды и повышенного содержания примесей мы подбираем модели с дополнительными ступенями умягчения — например, Pro RO или Ultra." },
    { q: "Сколько времени занимает установка?", a: "Обычно установка занимает от 40 минут до 2 часов в зависимости от модели и особенностей сантехники. Мастер приезжает по согласованному времени." },
    { q: "Даёте ли вы гарантию?", a: "Да, на оборудование и монтажные работы действует официальная гарантия. Подробные условия зависят от выбранной модели — уточним при оформлении заявки." },
    { q: "Как происходит оплата?", a: "Принимаем наличный и безналичный расчёт, а также переводы через популярные платёжные приложения. Способ оплаты можно согласовать с менеджером в Telegram." },
    { q: "Обслуживаете ли вы фильтр после установки?", a: "Да, мы сопровождаем клиента после покупки: напоминаем о замене картриджей и выезжаем на сервисное обслуживание при необходимости." },
  ],
  uz: [
    { q: "Kartrijlarni qancha vaqtda almashtirish kerak?", a: "O'rtacha 6–12 oyda bir marta, model va suv sifatiga qarab. Aniq muddat filtr pasportida ko'rsatiladi, biz esa almashtirish vaqtini oldindan eslatib turamiz." },
    { q: "Filtr juda qattiq suv uchun mosmi?", a: "Ha, qattiq suv va aralashmalar ko'p bo'lgan holatlar uchun qo'shimcha yumshatish bosqichlariga ega modellarni tanlaymiz — masalan, Pro RO yoki Ultra." },
    { q: "O'rnatish qancha vaqt oladi?", a: "Odatda 40 daqiqadan 2 soatgacha, modelga va santexnika xususiyatlariga qarab. Usta kelishilgan vaqtda keladi." },
    { q: "Kafolat berasizmi?", a: "Ha, uskuna va montaj ishlariga rasmiy kafolat beriladi. Aniq shartlari tanlangan modelga qarab farq qiladi — ariza berishda aniqlashtiramiz." },
    { q: "To'lov qanday amalga oshiriladi?", a: "Naqd va naqdsiz to'lovni, shuningdek mashhur to'lov ilovalari orqali o'tkazmalarni qabul qilamiz. To'lov usulini Telegramda menejer bilan kelishishingiz mumkin." },
    { q: "O'rnatishdan keyin filtrga xizmat ko'rsatasizmi?", a: "Ha, xarid qilgandan keyin ham mijoz bilan aloqada bo'lamiz: kartrijlarni almashtirish vaqtini eslatamiz va zarur bo'lsa servis uchun boramiz." },
  ],
};

const QUIZ = {
  ru: [
    {
      question: "Где будете использовать фильтр?",
      options: [
        { text: "Кухня, под мойку", scores: { "Vitarex Compact": 3, "Vitarex Standard": 1 } },
        { text: "Вся квартира или дом", scores: { "Vitarex Standard": 3, "Vitarex Pro RO": 1 } },
        { text: "Кафе, офис, бизнес", scores: { "Vitarex Ultra": 3 } },
      ],
    },
    {
      question: "Какая у вас вода из-под крана?",
      options: [
        { text: "Обычная, нареканий нет", scores: { "Vitarex Standard": 2, "Vitarex Compact": 1 } },
        { text: "Жёсткая / есть накипь на чайнике", scores: { "Vitarex Pro RO": 3, "Vitarex Ultra": 1 } },
        { text: "Не знаю, хочу максимум надёжности", scores: { "Vitarex Pro RO": 2, "Vitarex Standard": 1 } },
      ],
    },
    {
      question: "Что для вас важнее?",
      options: [
        { text: "Цена и компактность", scores: { "Vitarex Compact": 2 } },
        { text: "Глубина очистки", scores: { "Vitarex Pro RO": 2, "Vitarex Ultra": 1 } },
        { text: "Объём и скорость (много воды в день)", scores: { "Vitarex Ultra": 2, "Vitarex Standard": 1 } },
      ],
    },
  ],
  uz: [
    {
      question: "Filtrni qayerda ishlatasiz?",
      options: [
        { text: "Oshxona, rakovina ostida", scores: { "Vitarex Compact": 3, "Vitarex Standard": 1 } },
        { text: "Butun kvartira yoki uy", scores: { "Vitarex Standard": 3, "Vitarex Pro RO": 1 } },
        { text: "Kafe, ofis, biznes", scores: { "Vitarex Ultra": 3 } },
      ],
    },
    {
      question: "Jo'mrakdagi suvingiz qanday?",
      options: [
        { text: "Oddiy, shikoyat yo'q", scores: { "Vitarex Standard": 2, "Vitarex Compact": 1 } },
        { text: "Qattiq / choynakda oqlanish bor", scores: { "Vitarex Pro RO": 3, "Vitarex Ultra": 1 } },
        { text: "Bilmayman, maksimal ishonchlilik kerak", scores: { "Vitarex Pro RO": 2, "Vitarex Standard": 1 } },
      ],
    },
    {
      question: "Siz uchun nima muhimroq?",
      options: [
        { text: "Narx va ixchamlik", scores: { "Vitarex Compact": 2 } },
        { text: "Tozalash chuqurligi", scores: { "Vitarex Pro RO": 2, "Vitarex Ultra": 1 } },
        { text: "Hajm va tezlik (kuniga ko'p suv)", scores: { "Vitarex Ultra": 2, "Vitarex Standard": 1 } },
      ],
    },
  ],
};
