// Vitarex demo content. Replace with real product data, prices and photos.

const TRANSLATIONS = {
  ru: {
    demo_banner: "Демо-версия сайта. Товары, цены и фото — примеры для наполнения. Свяжитесь с нами, чтобы обсудить финальный вариант.",
    nav_about: "О нас",
    nav_catalog: "Каталог",
    nav_advantages: "Преимущества",
    nav_steps: "Как заказать",
    nav_reviews: "Отзывы",
    nav_faq: "FAQ",
    nav_contacts: "Контакты",
    header_cta: "Заказать",
    hero_eyebrow: "Premium suv tozalash filtri",
    hero_title_html: "Чистая вода в <em>каждом доме</em> — с фильтрами Vitarex",
    hero_chip_steps: "7 ступеней очистки",
    hero_chip_warranty: "Гарантия на монтаж",
    hero_sub: "Многоступенчатая очистка, простая установка и забота о здоровье вашей семьи. Каталог фильтров под любые задачи — от кухни до целого дома.",
    hero_cta_catalog: "Смотреть каталог",
    hero_cta_contact: "Получить консультацию",
    stat_followers: "подписчиков в Instagram",
    stat_steps_value: "до 7 ступеней",
    stat_steps: "очистки воды",
    stat_warranty_value: "гарантия",
    stat_warranty: "на фильтры и монтаж",
    about_eyebrow: "О компании",
    about_title: "Vitarex — гарантия здоровой и чистой воды",
    about_p1: "Мы поставляем и устанавливаем премиальные системы очистки воды для дома, офиса и бизнеса. Наша миссия — чтобы в каждом доме была вода, которой можно доверять.",
    about_p2: "Работаем напрямую с клиентом: подбираем модель под состав воды и задачи, доставляем, устанавливаем и остаёмся на связи для обслуживания.",
    about_li1: "Подбор фильтра под воду вашего района",
    about_li2: "Установка мастером и настройка системы",
    about_li3: "Сервисное обслуживание и замена картриджей",
    catalog_eyebrow: "Каталог",
    catalog_title: "Фильтр Vitarex",
    catalog_sub: "Премиальная система очистки воды с минерализацией. Фото и точная цена уточняются.",
    catalog_stages_title: "Как работает фильтр",
    catalog_advantages_title: "Преимущества",
    adv_eyebrow: "Почему мы",
    adv_title: "Преимущества Vitarex",
    steps_eyebrow: "Процесс",
    steps_title: "Как оформить заказ",
    reviews_eyebrow: "Отзывы",
    reviews_title: "Что говорят наши клиенты",
    reviews_sub: "Демо-отзывы для примера оформления блока — заменим на реальные отзывы клиентов.",
    faq_eyebrow: "Вопросы и ответы",
    faq_title: "Частые вопросы",
    faq_sub: "Не нашли ответ — напишите нам в Telegram, ответим лично.",
    contact_eyebrow: "Контакты",
    contact_title: "Готовы подобрать фильтр для вашего дома?",
    contact_sub: "Оставьте заявку или напишите нам напрямую — ответим и поможем с выбором модели.",
    form_title: "Быстрая заявка",
    form_name: "Ваше имя",
    form_name_ph: "Имя",
    form_phone: "Телефон",
    form_model: "Интересующая модель",
    form_submit: "Отправить в Telegram",
    form_hint: "Кнопка откроет Telegram с готовым сообщением для @Vitarex_admin.",
    footer_tag: "Premium suv tozalash filtri — sog'lom va toza suv kafolati.",
    footer_rights: "Все права защищены.",
    footer_demo: "Демо-сайт, созданный для наполнения реальными данными.",
    price_from: "от",
    price_currency: "сум",
    order_btn: "Заказать",
  },
  uz: {
    demo_banner: "Sayt demo-versiyasi. Mahsulotlar, narxlar va suratlar — namuna sifatida keltirilgan. Yakuniy variantni muhokama qilish uchun biz bilan bog'laning.",
    nav_about: "Biz haqimizda",
    nav_catalog: "Katalog",
    nav_advantages: "Afzalliklar",
    nav_steps: "Qanday buyurtma qilish",
    nav_reviews: "Fikrlar",
    nav_faq: "FAQ",
    nav_contacts: "Aloqa",
    header_cta: "Buyurtma berish",
    hero_eyebrow: "Premium suv tozalash filtri",
    hero_title_html: "Har bir <em>uyda toza suv</em> — Vitarex filtrlari bilan",
    hero_chip_steps: "7 bosqichli tozalash",
    hero_chip_warranty: "Montaj uchun kafolat",
    hero_sub: "Ko'p bosqichli tozalash, oson o'rnatish va oilangiz salomatligi haqida g'amxo'rlik. Har qanday ehtiyoj uchun filtrlar katalogi — oshxonadan butun uygacha.",
    hero_cta_catalog: "Katalogni ko'rish",
    hero_cta_contact: "Konsultatsiya olish",
    stat_followers: "Instagram obunachilari",
    stat_steps_value: "7 bosqichgacha",
    stat_steps: "suv tozalash",
    stat_warranty_value: "kafolat",
    stat_warranty: "filtr va montaj uchun",
    about_eyebrow: "Kompaniya haqida",
    about_title: "Vitarex — sog'lom va toza suv kafolati",
    about_p1: "Biz uy, ofis va biznes uchun premium suv tozalash tizimlarini yetkazib beramiz va o'rnatamiz. Bizning maqsadimiz — har bir uyda ishonch bildirsa bo'ladigan suv bo'lishi.",
    about_p2: "Mijoz bilan bevosita ishlaymiz: suv tarkibi va ehtiyojlarga qarab model tanlaymiz, yetkazib beramiz, o'rnatamiz va xizmat ko'rsatish uchun aloqada bo'lamiz.",
    about_li1: "Hududingiz suviga mos filtr tanlash",
    about_li2: "Usta tomonidan o'rnatish va sozlash",
    about_li3: "Servis xizmati va kartrijlarni almashtirish",
    catalog_eyebrow: "Katalog",
    catalog_title: "Vitarex filtri",
    catalog_sub: "Minerallashtirish bilan premium suv tozalash tizimi. Surat va aniq narx aniqlashtirilmoqda.",
    catalog_stages_title: "Filtr qanday ishlaydi",
    catalog_advantages_title: "Afzalliklari",
    adv_eyebrow: "Nega aynan biz",
    adv_title: "Vitarex afzalliklari",
    steps_eyebrow: "Jarayon",
    steps_title: "Buyurtmani qanday rasmiylashtirish",
    reviews_eyebrow: "Fikrlar",
    reviews_title: "Mijozlarimiz nima deyishadi",
    reviews_sub: "Blok dizayni uchun demo-fikrlar — haqiqiy mijoz fikrlariga almashtiramiz.",
    faq_eyebrow: "Savol-javob",
    faq_title: "Tez-tez so'raladigan savollar",
    faq_sub: "Javobini topolmadingizmi — Telegramga yozing, shaxsan javob beramiz.",
    contact_eyebrow: "Aloqa",
    contact_title: "Uyingiz uchun filtr tanlashga tayyormisiz?",
    contact_sub: "Ariza qoldiring yoki bevosita yozing — javob berib, model tanlashda yordam beramiz.",
    form_title: "Tezkor ariza",
    form_name: "Ismingiz",
    form_name_ph: "Ism",
    form_phone: "Telefon",
    form_model: "Qiziqtirgan model",
    form_submit: "Telegramga yuborish",
    form_hint: "Tugma @Vitarex_admin uchun tayyor xabar bilan Telegramni ochadi.",
    footer_tag: "Premium suv tozalash filtri — sog'lom va toza suv kafolati.",
    footer_rights: "Barcha huquqlar himoyalangan.",
    footer_demo: "Haqiqiy ma'lumotlar bilan to'ldirish uchun yaratilgan demo-sayt.",
    price_from: "dan",
    price_currency: "so'm",
    order_btn: "Buyurtma berish",
  },
};

const CATALOG = {
  ru: [
    {
      icon: "gauge",
      badge: "Обратный осмос",
      name: "Vitarex",
      tagline: "5-ступенчатый фильтр обратного осмоса",
      desc: "Премиальная система очистки воды с минерализацией — для дома и кухни.",
      specs: ["5 ступеней очистки", "2 л чистой воды в минуту", "0,8 л расхода на 1 л очищенной"],
      stages: [
        { title: "1–2 ступень — грубая очистка", text: "Задерживает ржавчину, песок, глину и крупные нерастворённые частицы." },
        { title: "3 ступень — очистка мембраной", text: "Вода проходит через мембрану — удаляется до 98% тяжёлых металлов, бактерий и химических веществ." },
        { title: "4 ступень — постактивация T33", text: "Угольный фильтр T33 полностью восстанавливает вкус и запах воды, возвращает естественную мягкость." },
        { title: "5 ступень — минерализация", text: "В очищенную воду добавляются полезные минералы — кальций, магний, калий." },
      ],
      advantages: [
        "Экономия воды — всего 0,8 л на 1 л чистой воды",
        "Скорость — 2 л чистой воды в минуту",
        "Не требует отдельной ёмкости для сбора воды",
        "Экономит электроэнергию",
      ],
      priceOnRequest: true,
      price: "Уточняйте у менеджера",
    },
  ],
  uz: [
    {
      icon: "gauge",
      badge: "Teskari osmos",
      name: "Vitarex",
      tagline: "5 bosqichli teskari osmos filtri",
      desc: "Minerallashtirish bilan premium suv tozalash tizimi — uy va oshxona uchun.",
      specs: ["5 bosqichli tozalash", "Daqiqasiga 2 l toza suv", "1 l toza suv uchun 0,8 l sarf"],
      stages: [
        { title: "1–2 bosqich — dag'al tozalash", text: "Zang, qum, loy va erimagan katta zarrachalar ushlab qolinadi." },
        { title: "3 bosqich — membrana orqali tozalash", text: "Suv maxsus membranadan o'tadi — og'ir metallar, bakteriyalar va kimyoviy moddalarning 98% gacha tozalanadi." },
        { title: "4 bosqich — T33 postaktivatsiya", text: "T33 ko'mir filtr suvning ta'mi va hidini to'liq tiklaydi, tabiiy yumshoqligi qaytadi." },
        { title: "5 bosqich — mineralizatsiya", text: "Tozalangan suvga foydali minerallar — kaltsiy, magniy, kaliy qo'shiladi." },
      ],
      advantages: [
        "Suv tejamkorligi — 1 litr toza suv uchun atigi 0,8 litr sarflanadi",
        "Tezlik — daqiqasiga 2 litr toza suv",
        "Suv yig'ish uchun alohida idish talab etilmaydi",
        "Elektr energiyasini tejaydi",
      ],
      priceOnRequest: true,
      price: "Menejerdan so'rang",
    },
  ],
};

const ADVANTAGES = {
  ru: [
    { icon: "layers", title: "Многоступенчатая очистка", text: "Удаляем хлор, тяжёлые металлы, бактерии и механические примеси." },
    { icon: "wrench", title: "Профессиональная установка", text: "Монтаж выполняют обученные мастера с гарантией на работу." },
    { icon: "truck", title: "Быстрая доставка", text: "Привозим и устанавливаем в удобное для вас время." },
    { icon: "refresh", title: "Сервис и картриджи", text: "Напоминаем о замене и всегда есть расходники в наличии." },
    { icon: "shield", title: "Гарантия качества", text: "Официальная гарантия на оборудование и монтажные работы." },
    { icon: "chat", title: "Поддержка 24/7", text: "На связи в Telegram и по телефону для любых вопросов." },
  ],
  uz: [
    { icon: "layers", title: "Ko'p bosqichli tozalash", text: "Xlor, og'ir metallar, bakteriya va mexanik aralashmalarni yo'qotamiz." },
    { icon: "wrench", title: "Professional o'rnatish", text: "Montajni tajribali ustalar kafolat bilan bajaradi." },
    { icon: "truck", title: "Tezkor yetkazib berish", text: "Sizga qulay vaqtda olib kelamiz va o'rnatamiz." },
    { icon: "refresh", title: "Servis va kartrijlar", text: "Almashtirish vaqtini eslatib turamiz, ehtiyot qismlar doim mavjud." },
    { icon: "shield", title: "Sifat kafolati", text: "Uskuna va montaj ishlariga rasmiy kafolat beramiz." },
    { icon: "chat", title: "24/7 qo'llab-quvvatlash", text: "Telegram va telefon orqali har doim aloqadamiz." },
  ],
};

const STEPS = {
  ru: [
    { title: "Выбираете модель", text: "Смотрите каталог или пишете нам — поможем подобрать фильтр." },
    { title: "Оформляете заявку", text: "Оставляете контакты в форме или пишете в Telegram." },
    { title: "Согласовываем детали", text: "Уточняем адрес, дату и особенности установки." },
    { title: "Устанавливаем и запускаем", text: "Мастер приезжает, монтирует систему и всё проверяет." },
  ],
  uz: [
    { title: "Model tanlaysiz", text: "Katalogni ko'ring yoki bizga yozing — filtr tanlashda yordam beramiz." },
    { title: "Ariza qoldirasiz", text: "Formada kontaktlaringizni qoldiring yoki Telegramga yozing." },
    { title: "Tafsilotlarni kelishamiz", text: "Manzil, sana va o'rnatish xususiyatlarini aniqlashtiramiz." },
    { title: "O'rnatib, ishga tushiramiz", text: "Usta kelib tizimni o'rnatadi va hammasini tekshiradi." },
  ],
};

const REVIEWS = {
  ru: [
    { name: "Азиз Т.", text: "Установили Vitarex Standard на кухне — вода стала намного чище на вкус. Мастер приехал вовремя и всё объяснил.", initial: "А" },
    { name: "Мадина Р.", text: "Заказывали Pro RO для дома. Понравилось, что подобрали модель именно под нашу воду.", initial: "М" },
    { name: "Шерзод К.", text: "Отличный сервис — напомнили о замене картриджа заранее. Рекомендую.", initial: "Ш" },
    { name: "Дилноза С.", text: "Compact встал под мойку без переделок кухни. Ушёл привкус хлора буквально с первого дня.", initial: "Д" },
    { name: "Жасур Б.", text: "От заявки до установки прошло всего два дня. Мастер аккуратно всё смонтировал и убрал за собой.", initial: "Ж" },
    { name: "Нигора А.", text: "Поставили Ultra в кафе — гости стали заказывать больше напитков на воде. Производительности хватает с запасом.", initial: "Н" },
    { name: "Отабек М.", text: "Писал в Telegram с вопросами перед покупкой — отвечали быстро и по делу, без навязывания.", initial: "О" },
    { name: "Камола Ю.", text: "Ребёнок наконец пьёт воду из-под фильтра без капризов. Вкус и правда стал мягче.", initial: "К" },
  ],
  uz: [
    { name: "Aziz T.", text: "Oshxonaga Vitarex Standard o'rnatildi — suv mazasi ancha yaxshilandi. Usta o'z vaqtida keldi va hammasini tushuntirdi.", initial: "A" },
    { name: "Madina R.", text: "Uy uchun Pro RO buyurtma qildik. Aynan bizning suvimizga mos model tanlashgani yoqdi.", initial: "M" },
    { name: "Sherzod Q.", text: "Ajoyib servis — kartrijni almashtirish vaqtini oldindan eslatishdi. Tavsiya qilaman.", initial: "S" },
    { name: "Dilnoza S.", text: "Compact rakovina ostiga oshxonani qayta ta'mirlamasdan o'rnatildi. Xlor hidi birinchi kunidan yo'qoldi.", initial: "D" },
    { name: "Jasur B.", text: "Arizadan o'rnatishgacha bor-yo'g'i ikki kun ketdi. Usta hammasini toza va aniq qildi.", initial: "J" },
    { name: "Nigora A.", text: "Kafega Ultra o'rnatdik — unumdorligi yetarli, mehmonlar suvli ichimliklarni ko'proq buyurtma qila boshladi.", initial: "N" },
    { name: "Otabek M.", text: "Sotib olishdan oldin Telegramga savol yozgandim — tez va aniq javob berishdi, ortiqcha taklif qilishmadi.", initial: "O" },
    { name: "Kamola Yu.", text: "Bolam endi filtr suvini injiqliksiz ichadi. Mazasi haqiqatan ham yumshoqroq bo'ldi.", initial: "K" },
  ],
};

const FAQ = {
  ru: [
    { q: "Как часто нужно менять картриджи?", a: "В среднем раз в 6–12 месяцев в зависимости от модели и качества исходной воды. Точный интервал указывается в паспорте конкретного фильтра, а мы напоминаем о замене заранее." },
    { q: "Подходит ли фильтр для очень жёсткой воды?", a: "Да, для жёсткой воды и повышенного содержания примесей мы подбираем модели с дополнительными ступенями умягчения — например, Pro RO или Ultra." },
    { q: "Сколько времени занимает установка?", a: "Обычно установка занимает от 40 минут до 2 часов в зависимости от модели и особенностей сантехники. Мастер приезжает по согласованному времени." },
    { q: "Даёте ли вы гарантию?", a: "Да, на оборудование и монтажные работы действует официальная гарантия. Подробные условия зависят от выбранной модели — уточним при оформлении заявки." },
    { q: "Как происходит оплата?", a: "Принимаем наличный и безналичный расчёт, а также переводы через популярные платёжные приложения. Способ оплаты можно согласовать с менеджером в Telegram." },
    { q: "Обслуживаете ли вы фильтр после установки?", a: "Да, мы сопровождаем клиента после покупки: напоминаем о замене картриджей и выезжаем на сервисное обслуживание при необходимости." },
  ],
  uz: [
    { q: "Kartrijlarni qancha vaqtda almashtirish kerak?", a: "O'rtacha 6–12 oyda bir marta, model va suv sifatiga qarab. Aniq muddat filtr pasportida ko'rsatiladi, biz esa almashtirish vaqtini oldindan eslatib turamiz." },
    { q: "Filtr juda qattiq suv uchun mosmi?", a: "Ha, qattiq suv va aralashmalar ko'p bo'lgan holatlar uchun qo'shimcha yumshatish bosqichlariga ega modellarni tanlaymiz — masalan, Pro RO yoki Ultra." },
    { q: "O'rnatish qancha vaqt oladi?", a: "Odatda 40 daqiqadan 2 soatgacha, modelga va santexnika xususiyatlariga qarab. Usta kelishilgan vaqtda keladi." },
    { q: "Kafolat berasizmi?", a: "Ha, uskuna va montaj ishlariga rasmiy kafolat beriladi. Aniq shartlari tanlangan modelga qarab farq qiladi — ariza berishda aniqlashtiramiz." },
    { q: "To'lov qanday amalga oshiriladi?", a: "Naqd va naqdsiz to'lovni, shuningdek mashhur to'lov ilovalari orqali o'tkazmalarni qabul qilamiz. To'lov usulini Telegramda menejer bilan kelishishingiz mumkin." },
    { q: "O'rnatishdan keyin filtrga xizmat ko'rsatasizmi?", a: "Ha, xarid qilgandan keyin ham mijoz bilan aloqada bo'lamiz: kartrijlarni almashtirish vaqtini eslatamiz va zarur bo'lsa servis uchun boramiz." },
  ],
};
